a=float(input("Enter first Number"))
b=float(input("Enter second Number"))
c=float(input("Enter third Number"))
d=float(input("Enter fourth Number"))
p=(a*b*c*d)
print("Before ;",p)
print("after ;",int(p))